name: flutter_contact
version: 0.6.4+1
homepage: https://github.com/SunnyApp/flutter_contact
description: A Flutter plugin to retrieve, create and save contacts and contact-related events on Android and iOS devices.
maintainer: Eric Martineau
environment: 
  sdk: '>=2.6.0 <3.0.0'
  flutter: ^1.10.0
dependencies: 
  uuid: ^3.0.1
  permission_handler: ^5.0.1+1
  logging: ^1.0.1
  logging_config: ^0.6.7+6
  equatable: ^2.0.0
  collection: ^1.14.11
  quiver: ^3.0.0
  sunny_dart: ^0.10.0+2
  intl: ^0.17.0
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  plugin: 
    platforms: 
      android: 
        package: co.sunnyapp.flutter_contact
        pluginClass: FlutterContactPlugin
      ios: 
        pluginClass: FlutterContactPlugin
